<a href="https://colab.research.google.com/github/JonathanSum/pytorch-Deep-Learning_colab/blob/master/Ch3Pytorch_Load_H5py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/deep-learning-with-pytorch/dlwpt-code.git

Cloning into 'dlwpt-code'...
remote: Enumerating objects: 686, done.
remote: Total 686 (delta 0), reused 0 (delta 0), pack-reused 686
Receiving objects: 100% (686/686), 176.00 MiB | 22.98 MiB/s, done.
Resolving deltas: 100% (296/296), done.
Checking out files: 100% (228/228), done.


In [2]:
!conda install h5py

/bin/bash: conda: command not found


In [5]:
import torch 
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

Two ways to save the points tensor

In [14]:
torch.save(points, "ourpoints.t")

In [16]:
with open('ourpoints.t','wb') as f:
    torch.save(points, f)

Loading examples

In [17]:
points = torch.load('ourpoints.t')
#Or another way
with open('ourpoints.t','rb') as f:
    points = torch.load(f)  

In [29]:
import h5py
f = h5py.File('ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

Here 'coords' is a key into the HDF5 file. We can have other keys—even nested ones.<br>
One of the interesting things in HDF5 is that we can index the dataset while on disk<br>
and access only the elements we’re interested in. Let’s suppose we want to load just<br>
the last two points in our dataset:<br>
(Cite: Pytorch deep learning book)

In [33]:
f = h5py.File('ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]

In [37]:
dset

<HDF5 dataset "coords": shape (3, 4), type "<f4">

In [41]:
last_points

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [40]:
points.numpy()

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [42]:
f.close()

In [43]:
last_points

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [79]:
a = torch.tensor(list(range(9))[::-1])

In [80]:
a

tensor([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [81]:
a.storage_offset()

0

In [88]:
 b = a.view(3, 3)
 b

tensor([[8, 7, 6],
        [5, 4, 3],
        [2, 1, 0]])

In [83]:
b.storage_offset()

0

In [84]:
b.stride()


(3, 1)

In [90]:
c = b[2:,1:]
c

tensor([[1, 0]])

In [91]:
c.storage_offset()

7

In [92]:
t1 = torch.tensor([4,4])

In [97]:
t1.float()

tensor([4., 4.])

In [98]:
torch.sqrt(t1.float())

tensor([2., 2.])

In [96]:
t1

tensor([4, 4])

3.14 Exercises<br>
1 Create a tensor a from list(range(9)). Predict and then check the size,<br> offset,<br>
and stride.<br>
a Create a new tensor using b = a.view(3, 3). What does view do? Check<br>
that a and b share the same storage.<br>
b Create a tensor c = b[1:,1:]. Predict and then check the size, offset, and<br>
stride.<br>
2 Pick a mathematical operation like cosine or square root. Can you find a<br> corresponding function in the torch library?<br>
a Apply the function element-wise to a. Why does it return an error?<br>
b What operation is required to make the function work?<br>
c Is there a version of your function that operates in place?<br>